# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\x12\x05unary\"%\n\x10HandshakeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\'\n\x11HandshakeResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\"c\n\nRunRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x16\n\tcandidate\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06kwargs\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0c\n\n_candidateB\t\n\x07_kwargs\"\x83\x01\n\x0bRunResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06ranked\x18\x02 \x01(\x08\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x12\n\x05logit\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tembedding\x18\x05 \x01(\x0cH\x01\x88\x01\x01\x42\x08\n\x06_logitB\x0c\n\n_embedding\"S\n\rEncodeRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\treduction\x18\x03 \x01(\t\x12\x13\n\x06kwargs\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_kwargs\"4\n\x0e\x45ncodeResponse\x12\x11\n\tembedding\x18\x01 \x01(\x0c\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\xc1\x01\n\x0cQueryService\x12@\n\tHandshake\x12\x17.unary.HandshakeRequest\x1a\x18.unary.HandshakeResponse\"\x00\x12;\n\x06\x45ncode\x12\x14.unary.EncodeRequest\x1a\x15.unary.EncodeResponse\"\x00(\x01\x30\x01\x12\x32\n\x03Run\x12\x11.unary.RunRequest\x1a\x12.unary.RunResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDSHAKEREQUEST']._serialized_start=22
  _globals['_HANDSHAKEREQUEST']._serialized_end=59
  _globals['_HANDSHAKERESPONSE']._serialized_start=61
  _globals['_HANDSHAKERESPONSE']._serialized_end=100
  _globals['_RUNREQUEST']._serialized_start=102
  _globals['_RUNREQUEST']._serialized_end=201
  _globals['_RUNRESPONSE']._serialized_start=204
  _globals['_RUNRESPONSE']._serialized_end=335
  _globals['_ENCODEREQUEST']._serialized_start=337
  _globals['_ENCODEREQUEST']._serialized_end=420
  _globals['_ENCODERESPONSE']._serialized_start=422
  _globals['_ENCODERESPONSE']._serialized_end=474
  _globals['_QUERYSERVICE']._serialized_start=477
  _globals['_QUERYSERVICE']._serialized_end=670
# @@protoc_insertion_point(module_scope)
